#pragma once

#define COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, CONST, A, B)	\
	vec<2, T, Q> A ## B() CONST							\
	{													\
		return vec<2, T, Q>(this->A, this->B);			\
	}

#define COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, CONST, A, B, C)		\
	vec<3, T, Q> A ## B ## C() CONST							\
	{															\
		return vec<3, T, Q>(this->A, this->B, this->C);			\
	}

#define COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, CONST, A, B, C, D)					\
	vec<4, T, Q> A ## B ## C ## D() CONST									\
	{																		\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D);			\
	}

#define COBALT_SWIZZLE_GEN_VEC2_ENTRY_DEF(T, P, L, CONST, A, B)	\
	template<typename T>										\
	vec<L, T, Q> vec<L, T, Q>::A ## B() CONST					\
	{															\
		return vec<2, T, Q>(this->A, this->B);					\
	}

#define COBALT_SWIZZLE_GEN_VEC3_ENTRY_DEF(T, P, L, CONST, A, B, C)		\
	template<typename T>											\
	vec<3, T, Q> vec<L, T, Q>::A ## B ## C() CONST					\
	{																\
		return vec<3, T, Q>(this->A, this->B, this->C);				\
	}

#define COBALT_SWIZZLE_GEN_VEC4_ENTRY_DEF(T, P, L, CONST, A, B, C, D)		\
	template<typename T>												\
	vec<4, T, Q> vec<L, T, Q>::A ## B ## C ## D() CONST					\
	{																	\
		return vec<4, T, Q>(this->A, this->B, this->C, this->D);		\
	}

#define COBALT_MUTABLE

#define COBALT_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, 2, COBALT_MUTABLE, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, 2, COBALT_MUTABLE, B, A)

#define COBALT_SWIZZLE_GEN_REF_FROM_VEC2(T, P) \
	COBALT_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, x, y) \
	COBALT_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, r, g) \
	COBALT_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, s, t)

#define COBALT_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, A, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, B, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, C, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, C, B)

#define COBALT_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, COBALT_MUTABLE, C, B, A)

#define COBALT_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE(T, P, A, B, C)

#define COBALT_SWIZZLE_GEN_REF_FROM_VEC3(T, P) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, x, y, z) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, r, g, b) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, s, t, p)

#define COBALT_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, A, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, A, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, B, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, B, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, C, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, C, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, C, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, D, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, D, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, COBALT_MUTABLE, D, C)

#define COBALT_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, C, B)

#define COBALT_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, C, A)

#define COBALT_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)

#define COBALT_SWIZZLE_GEN_REF_FROM_VEC4(T, P) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, x, y, z, w) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, r, g, b, a) \
	COBALT_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, s, t, p, q)

#define COBALT_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B)

#define COBALT_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, B)

#define COBALT_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, B)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE(T, P, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE(T, P, A, B)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC2(T, P)			\
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, x, y)	\
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, r, g)	\
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, s, t)

#define COBALT_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, C)

#define COBALT_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, C)

#define COBALT_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, C)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE(T, P, A, B, C)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC3(T, P) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, x, y, z) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, r, g, b) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, s, t, p)

#define COBALT_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, D) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, A) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, B) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, C) \
	COBALT_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, D)

#define COBALT_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, D, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, D, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, D, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, A, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, A, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, B, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, B, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, C, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, D, A) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, D, B) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, D, C) \
	COBALT_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, D, D, D)

#define COBALT_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, C, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, D, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, C, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, D, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, A, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, B, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, C, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, C, D, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, A, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, B, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, C, D, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, A, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, A, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, A, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, A, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, B, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, B, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, B, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, B, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, C, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, C, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, C, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, D, A) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, D, B) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, D, C) \
	COBALT_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, D, D, D, D)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \
	COBALT_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)

#define COBALT_SWIZZLE_GEN_VEC_FROM_VEC4(T, P) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, x, y, z, w) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, r, g, b, a) \
	COBALT_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, s, t, p, q)

